### PR TITLE
Change PHP keywords to comply with PSR2

### PR DESCRIPTION
**Pull request by mullikine**
Hi, I've changed a PHP keyword to comply with [this standard](https://www.php-fig.org/psr/psr-2/#25-keywords-and-truefalsenull) in PSR2. It's admittedly a small fix but I hope it helps!

### CODE REVIEW

**Comment by FreeSS** [comment]
@mullikine thank you for contribution!

**Comment by FreeSS** [comment]
@mullikine Hello! Can you resolve conflict on this PR?

**Comment by mullikine** [comment]
> @mullikine Hello! Can you resolve conflict on this PR?

No worries!

**Comment by mullikine** [comment]
I've re-run the bot! Looks like it did the right thing :)

**Comment by FreeSS** [comment]
@mullikine Thanks :)

**Pull request merged**
